# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 13:50
from __future__ import unicode_literals

import displayWidgets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_config', models.TextField(default=displayWidgets.models.initial_config, max_length=5000)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
